#!/bin/sh /etc/rc.common

# نام سرویس شما
USE_PROCD=1
START=99
STOP=15

# مسیر اسکریپت اصلی که باید اجرا شود
SERVICE_SCRIPT="/usr/bin/internet_led_status.sh"

# تابع start_service: توسط procd برای شروع سرویس فراخوانی می‌شود
start_service() {
    procd_open_instance
    procd_set_param command /bin/sh "$SERVICE_SCRIPT"
    # راه‌اندازی مجدد خودکار در صورت بروز خطا
    procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_delay:-5}
    procd_close_instance
}
